
endpoints:
  health:
    sensitive: true

management:
  security:
    enabled: false
    
spring:
  boot:
    admin:
      url: http://monitor:8081
  application:
    name: Authentication
    

server:
  port: 9001
  context-path: /auth
  
security:
  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG